---
title: "reporting_BM"
output: html_document
date: "2026-04-15"
---

```{r}
# for markdown
library(kableExtra)
```

```{r}
# Prepare session
# Packages
library(dplyr)
library(arules)
library(arulesViz)
library(ggplot2)
library(ulrb)
library(stringr)
library(tidyr)
library(ggpubr)
library(tidyr)
library(ggVennDiagram)
library(purrr)
library(gridExtra)
# vector colors
qualitative_colors <- 
  c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
reds <- RColorBrewer::brewer.pal(9, "Reds")

```


```{r}
# Bank marketing dataset
## Breast cancer - new case study
bank_marketing_df <- read.csv("../data/bank-full.csv", sep = ";")

## numeric vars to categoric -- case by case
bank_marketing_cat <- bank_marketing_df %>% 
  mutate(age = as.factor(age), 
         day = as.factor(day),
         campaign = as.factor(campaign),
         pdays = case_when(pdays == -1 ~ "Not contacted before",
                           pdays < 180 ~ "<6m",
                           pdays < 360 ~ "<1y",
                           TRUE ~ ">1y"),
         previous = case_when(pdays == -1 ~ "Not contacted before",
                              pdays < 180 ~ "<6m",
                              pdays < 360 ~ "<1y",
                              TRUE ~ ">1y"),
         balance = case_when(balance < 0 ~ "Negative",
                             balance <= 72 ~ "vlow",
                             balance <= 448 ~ "low",
                             balance <= 1428 ~ "high",
                             TRUE ~ "vhigh"),
         duration = case_when(duration == 0 ~ "No call",
                              duration <103 ~ "vshort",
                              duration < 180 ~ "short",
                              duration < 319 ~ "long",
                              duration <= 4918 ~ "vlong")
         )


# view distribution of vars -- sup material
bank_marketing_transactions <- bank_marketing_cat %>% transactions()

#
#View(DATAFRAME(bank_marketing_transactions))
#

# get rhs items (set the consequent)
subscription_rhs <- grep("y=", 
                      itemLabels(bank_marketing_transactions), 
                      value = TRUE)

#
subscription_rules <- apriori(bank_marketing_transactions,
                           parameter = list(support = 0.001, 
                                            minlen = 2, maxlen = 18),
                           appearance = list(rhs = subscription_rhs))
#
#subscription_rules %>% DATAFRAME() %>% View()
subscription_rules_df <- subscription_rules %>% DATAFRAME()

# AIRI steps

## Step 1 - identify dependent rules
# Chi-square test
subscription_rules_df$chi_p_adj <- 
  subscription_rules %>% 
  interestMeasure(measure = "chiSquared", 
                  significance = TRUE) %>% 
  p.adjust(method = "bonferroni") ## adjust p-values

# Calculate conviction
subscription_rules_df$Conviction <- subscription_rules %>% 
  interestMeasure(measure = "Conviction")

# update dataframe
subscription_rules_df_dependent <- 
  subscription_rules_df %>% 
  mutate(Dependence = ifelse(chi_p_adj <0.05, "Dependent", "Independent")) %>% # add test result 
  filter(Dependence == "Dependent")# select dependent rules

# Add new metrics to rules objects
quality(subscription_rules)$conviction <- subscription_rules_df$Conviction
quality(subscription_rules)$chi_p_adj <- subscription_rules_df$chi_p_adj

# filter dependent rules
subscription_rules_dependent <- subscription_rules[quality(subscription_rules)$chi_p_adj<0.05,]

# statistics
subscription_rules_df %>% 
  mutate(Dependence = ifelse(chi_p_adj <0.05, "Dependent", "Independent")) %>%
  pull(Dependence) %>% table()

#
## Step 2 - remove redundant rules
# Calculate Mutual information and Improvement
quality(subscription_rules_dependent)$mutualInfo <- interestMeasure(subscription_rules_dependent,
                                                                 measure = "mutualInformation")
quality(subscription_rules_dependent)$improvement <- interestMeasure(subscription_rules_dependent,
                                                                  measure = "improvement")
#
subscription_rules_dependent_df <- subscription_rules_dependent %>% DATAFRAME()
#subscription_rules_dependent %>% DATAFRAME() %>% View()

## dependent rules - nonredundant
# key item is worst measurement of any var
bal_key <- grep("balance=", 
     itemLabels(bank_marketing_transactions), 
     value = TRUE)
edu_key <- grep("education=", 
     itemLabels(bank_marketing_transactions), 
     value = TRUE)
age_key <- grep("age=", 
     itemLabels(bank_marketing_transactions), 
     value = TRUE)
#

# Remove redundancy by Improvement
#
subscription_rules_non_redundant_improv <- subscription_rules_dependent %>% 
  DATAFRAME() %>%
  mutate(age_key = str_extract(LHS, paste(c(age_key), collapse = "|")),
         bal_key = str_extract(LHS, paste(c(bal_key), collapse = "|")),
         edu_key = str_extract(LHS, paste(c(edu_key), collapse = "|"))) %>% 
  mutate(Key = paste(age_key, bal_key, edu_key)) %>% 
  filter(Key != "NA NA NA") %>% 
  group_by(Key) %>% 
  arrange(desc(improvement)) %>% 
  slice_head(n = 1) %>% 
  ungroup() %>% 
  select(Key, LHS, RHS, support,
         confidence, coverage,	
         lift,	count,	conviction,	
         mutualInfo,	improvement)

subscription_rules_non_redundant_improv %>% kable()

##
subscription_rules_non_redundant_mutualInfo <- subscription_rules_dependent %>% 
  DATAFRAME() %>%
  mutate(age_key = str_extract(LHS, paste(c(age_key), collapse = "|")),
         bal_key = str_extract(LHS, paste(c(bal_key), collapse = "|")),
         edu_key = str_extract(LHS, paste(c(edu_key), collapse = "|"))) %>% 
  mutate(Key = paste(age_key, bal_key, edu_key)) %>% 
  filter(Key != "NA NA NA") %>% 
  group_by(Key) %>% 
  arrange(desc(mutualInfo)) %>% 
  slice_head(n = 1) %>% 
  ungroup() %>% 
  select(Key, LHS, RHS, support,
         confidence, coverage,	
         lift,	count,	conviction,	
         mutualInfo,	improvement) 

subscription_rules_non_redundant_mutualInfo %>% kable()


#
subscription_rules_non_redundant_complex <- subscription_rules_dependent %>% 
  DATAFRAME() %>%
  mutate(LHSsize = str_count(LHS, ",")) %>% 
  mutate(age_key = str_extract(LHS, paste(c(age_key), collapse = "|")),
         bal_key = str_extract(LHS, paste(c(bal_key), collapse = "|")),
         edu_key = str_extract(LHS, paste(c(edu_key), collapse = "|"))) %>% 
  mutate(Key = paste(age_key, bal_key, edu_key)) %>% 
  filter(Key != "NA NA NA") %>% 
  group_by(Key) %>% 
  arrange(desc(LHSsize)) %>% 
  slice_head(n = 1) %>% 
  ungroup() %>% 
  select(Key, LHS, RHS, support,
         confidence, coverage,	
         lift,	count,	conviction,	
         mutualInfo,	improvement) 

subscription_rules_non_redundant_complex %>% kable()

## plots
ggVennDiagram(x = list(subscription_rules_non_redundant_mutualInfo$LHS,
                       subscription_rules_non_redundant_complex$LHS,
                       subscription_rules_non_redundant_improv$LHS),
              category.names = c("Mutual\nInformation",
                                 "Complexity",
                                 "Improvement"),
              label_size = 4) + 
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF") +
  guides(fill = "none") +
  labs(title = "Dataset: Bank Marketing",
       subtitle = "Key: Education, age and balance") + 
  xlim(-6,9)+
  ylim(-9,6)

# summary
subscription_rules_non_redundant_mutualInfo$Metric <- "Mutual\ninformation"
subscription_rules_non_redundant_complex$Metric <- "Complexity"
subscription_rules_non_redundant_improv$Metric <-"Improvement"   

subscription_all_non_redundant <- 
  rbind(subscription_rules_non_redundant_mutualInfo,
        subscription_rules_non_redundant_complex,
        subscription_rules_non_redundant_improv) 

#
gridExtra::grid.arrange(
  subscription_all_non_redundant %>% 
    ggplot(aes(Metric, confidence)) + 
    geom_boxplot(outliers = FALSE) + 
    geom_jitter(height = 0, width = 0.1, col = "grey7") +
    theme_classic() + 
    theme(axis.title.x = element_blank())+
    labs(y = "Confidence"),
  subscription_all_non_redundant %>% 
    ggplot(aes(Metric, lift)) + 
    geom_boxplot(outliers = FALSE) +
    geom_jitter(height = 0, width = 0.1, col = "grey7") +
    theme_classic() + 
    theme(axis.title.x = element_blank())+
    labs(y = "Lift"),
  subscription_all_non_redundant %>% 
    ggplot(aes(Metric, conviction)) + 
    geom_boxplot(outliers = FALSE) + 
    geom_jitter(height = 0, width = 0.1, col = "grey7") +
    theme_classic() +
    theme(axis.title.x = element_blank())+
    labs(y = "Conviction"), ncol = 3)


## this plot takes a long time (few minutes)
gridExtra::grid.arrange(
  subscription_rules_df %>% 
    ggplot(aes(support, confidence, col = lift)) + 
    geom_jitter(size = 2) + 
    scale_color_gradient(low = reds[1], high = reds[9]) + 
    theme_classic() + 
    theme(legend.position = "top",
          axis.title = element_text(size = 16),
          axis.text = element_text(size = 14),
          legend.text = element_text(size = 12),
          legend.title = element_text(size = 14),
          panel.background = element_rect(fill = "grey80")) + 
    labs(x = "Conviction",
         y = "Confidence"),
  subscription_rules_dependent_df %>% 
    ggplot(aes(support, confidence, col = lift)) + 
    geom_jitter(size = 2) + 
    scale_color_gradient(low = reds[1], high = reds[9]) + 
    theme_classic() + 
    theme(legend.position = "top",
          axis.title = element_text(size = 16),
          axis.text = element_text(size = 14),
          legend.text = element_text(size = 12),
          legend.title = element_text(size = 14),
          panel.background = element_rect(fill = "grey80")) + 
    labs(x = "Conviction",
         y = "Confidence")
)


## jaccard index --> proxy to redundancy between rule sets
bm_items <- names(bank_marketing_cat)[-17]

#
jaccard_all <- function(ruleset){
  # jaccard formula for sets a and b
  jaccard <- function(a, b){
    intersection = length(intersect(a, b))
    union = length(a) + length(b) - intersection
    return(intersection/union)
    }
  # to get possible comparisons between rules
  set_comparisons <- function(ruleset = ruleset){
    #  
    comparisons <- expand.grid(seq_along(ruleset$LHS), seq_along(ruleset$LHS))
    #
    comparisons <- data.frame(t(apply(comparisons, 1, sort))) %>% 
      distinct()
    #
    comparisons <- comparisons %>% 
      mutate(check = X1 - X2) %>% 
      filter(check != 0) %>% 
      select(-check)
    #
    return(comparisons)
  }
  #
  comparisons <- set_comparisons(ruleset = ruleset)
  
  # to calculate jaccard between two rules
  ruleJaccard <- function(ruleset, p1, p2){
    #
    rule_items <- ruleset %>% 
      mutate(item_sets = str_extract_all(LHS, paste(bm_items, collapse='|'))) %>% 
      pull(item_sets)
    #
    a <- rule_items[[p1]]
    b <- rule_items[[p2]]
    #
    jaccard_ab <- jaccard(a,b)
    #
    return(jaccard_ab)
  }
  
  # obtain ruleJaccard for all possible two rules
  jaccard_for_all <- map2(.x = comparisons$X1,
                          .y = comparisons$X2,
                          .f = ~ruleJaccard(ruleset, 
                                            p1 = .x, 
                                            p2 = .y)) %>% 
    unlist()
  
  #
  return(jaccard_for_all)
}

# apply to all
jaccard_scores_df <- subscription_all_non_redundant %>% 
  group_by(RHS, Metric) %>% 
  nest() %>% 
  mutate(jaccard = map(.x = data, .f = ~jaccard_all(.x)))

# points
jaccard_scores_df %>%
  unnest(jaccard) %>% 
  ggplot(aes(Metric, jaccard, col = RHS)) + 
  geom_jitter(height = 0, width = 0.1, alpha = 0.25) +
  stat_summary() + 
  labs(title = "Jaccard score for pairwise rules",
       subtitle = "Bank Marketing dataset \npairwise rule comparisons: 2129") + 
  theme_classic()

# violin
jaccard_scores_df %>%
  unnest(jaccard) %>% 
  ggplot(aes(Metric, jaccard, col = RHS)) + 
  #geom_jitter(height = 0, width = 0.1, alpha = 0.5) + 
  geom_violin(aes(fill = RHS)) + 
  stat_summary() + 
  labs(title = "Jaccard score for pairwise rules",
       subtitle = "Bank Marketing dataset \npairwise rule comparisons: 2129") + 
  theme_classic()

# summary
jaccard_scores_df %>%
  mutate(mean_jaccard = map(.x = jaccard, ~mean(.x)),
         sd_jaccard = map(.x = jaccard, ~sd(.x)),
         min_jaccard = map(.x = jaccard, ~min(.x)),
         max_jaccard = map(.x = jaccard, ~max(.x))) %>% 
  unnest(c(mean_jaccard, sd_jaccard, min_jaccard, max_jaccard)) 


## overall (for general compar)
subscription_all_non_redundant %>% 
  group_by(Metric) %>% 
  nest() %>% 
  mutate(jaccard = map(.x = data, .f = ~jaccard_all(.x))) %>% 
  mutate(mean_jaccard = map(.x = jaccard, ~mean(.x)),
         sd_jaccard = map(.x = jaccard, ~sd(.x))) %>% 
  unnest(c(mean_jaccard, sd_jaccard))

```

